apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: default
  labels:
    app: logger
  name: logger
spec:
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - image: ubuntu:18.04
        name: logger
        args: [/bin/sh, -c, 'sleep infinity']
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers